site_name: Boats Animator
pages:
- Home: index.md
- Introduction:
    - 'About Boats Animator': introduction/about.md
    - 'System requirements': introduction/system-requirements.md
- 'Getting started':
    - License: getting-started/license.md
    - Setup: getting-started/setup.md
- 'Features':
    - 'Launcher window': features/launcher-window.md
    - 'Main window': features/main-window.md
theme: readthedocs
extra_css: [css/custom.css]
site_dir: bin/site