name: "Add new issues to project"
on:
  issues:
    types:
      - opened
jobs:
  add-new-issues-to-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/charlielee/projects/1
          github-token: ${{ secrets.ADD_NEW_ISSUES_TO_PROJECT_TOKEN }}
